### PR TITLE
kafka auth: add sasl/scram mechanism

### PR DESCRIPTION
**Pull request by rccrdpccl**
Add possibility to use SASL/SCRAM mechanism.
This is useful as moving away from RHOSAK we are likely to need support for it

### CODE REVIEW

**Comment by rccrdpccl** [comment]
> some looks weird with the PR title and the PR itself: Screenshot from 2023-05-09 20-01-22

:facepalm: You're right, I've ammended the previous commit instead of making a new one by mistake...

**Comment by danmanor** [comment]
I might be wrong here, but in `Dockerfile.build` there is -
`go install github.com/golang/mock/mockgen@v1.5.0` which is attempting to install `1.5.0` but in the `go.mod` file there is
`github.com/golang/mock v1.6.0`, which requires `version >= v1.6.0`. Isn't it a problem?

**Comment by danmanor** [comment]
However I see that it has been like that for a long time so I guess that is not the issue

**Pull request merged**
